CREATE TABLE IF NOT EXISTS users (
                                    user_id int generated by default as identity primary key,
                                    email varchar(50) not null,
                                    login varchar(20) not null,
                                    name varchar(50),
                                    birthday date not null
);

CREATE TABLE IF NOT EXISTS status (
                                      status_id int generated by default as identity primary key,
                                      status_name int not null
);

CREATE TABLE IF NOT EXISTS rating (
                                      rating_id int generated by default as identity primary key,
                                      rating_name varchar(100) not null
);

CREATE TABLE IF NOT EXISTS genre (
                                     genre_id int generated by default as identity primary key,
                                     name varchar(20) not null
);

CREATE TABLE IF NOT EXISTS friends (
                                       friends_id int generated by default as identity primary key,
                                       user_id int not null,
                                       friend_id int not null,
                                       status_id int not null,
                                       CONSTRAINT fk_user_friend FOREIGN KEY (user_id) REFERENCES users(user_id),
                                       CONSTRAINT fk_friend_friend FOREIGN KEY (friend_id) REFERENCES users(user_id),
                                       CONSTRAINT fk_status_friend FOREIGN KEY (status_id) REFERENCES status(status_id)
);

CREATE TABLE IF NOT EXISTS user_likes (
                                          like_id int generated by default as identity primary key,
                                          user_id int not null,
                                          film_id int not null,
                                          CONSTRAINT fk_film_like FOREIGN KEY (film_id) REFERENCES film(film_id),
                                          CONSTRAINT fk_user_like FOREIGN KEY (user_id) REFERENCES users (user_id)
);

CREATE TABLE IF NOT EXISTS film (
                                    film_id int generated by default as identity primary key,
                                    name varchar(100) not null,
                                    description varchar(200) not null,
                                    release_date date not null,
                                    duration int,
                                    rating_id int,
                                    CONSTRAINT fk_rating_film FOREIGN KEY (rating_id) REFERENCES rating (rating_id)
);

CREATE TABLE IF NOT EXISTS genres (
                                      genres_id int generated by default as identity primary key,
                                      film_id int not null,
                                      genre_id int not null,
                                      CONSTRAINT fk_genres_film FOREIGN KEY (film_id) REFERENCES film (film_id),
                                      CONSTRAINT fk_genres_genre FOREIGN KEY (genre_id) REFERENCES genre (genre_id)
);